// ══════════════════════════════════════════════════════════════════
// KAYNAKLAR — Ücretsiz, herkese açık referans içerikleri
// SEO stratejisi: long-tail arama trafiği + backlink mıknatısı
// ══════════════════════════════════════════════════════════════════

// ── TİYATRO SÖZLÜĞÜ ───────────────────────────────────────────────
export type Term = {
  slug: string
  term: string
  termEn?: string
  short: string       // tek cümlelik tanım (schema description)
  body: string        // genişletilmiş açıklama
  group: 'oyunculuk' | 'yazarlık' | 'sahne' | 'müzikal' | 'tarih'
  related?: string[]  // diğer terim slug'ları
  link?: { label: string; href: string }  // ilgili program
}

export const TERMS: Term[] = [
  // ── OYUNCULUK ──
  {
    slug: 'stanislavski-sistemi',
    term: 'Stanislavski Sistemi',
    termEn: 'Stanislavski System',
    group: 'oyunculuk',
    short: 'Konstantin Stanislavski\'nin geliştirdiği, oyuncunun karakterin iç yaşamını psikolojik gerçeklikle inşa etmesine dayanan oyunculuk yöntemi.',
    body: 'Rus yönetmen Konstantin Stanislavski (1863–1938) tarafından Moskova Sanat Tiyatrosu\'nda geliştirildi. Temel sorusu şudur: "Karakterim bu sahnede ne istiyor?" Oyuncu, karakterin amacını (objective), önündeki engeli (obstacle) ve amaca ulaşmak için kullandığı eylemi (action) netleştirir. Duygu doğrudan üretilmez — eylemin sonucu olarak ortaya çıkar. Modern oyunculuk eğitiminin neredeyse tamamı bu sistemin ya devamı ya da ona verilmiş bir yanıttır.',
    related: ['duygusal-bellek', 'verili-durumlar', 'method-acting', 'sihirli-eger'],
    link: { label: 'Oyuncunun Mevcudiyeti', href: '/atolyeler/oyuncunun-mevcudiyeti' },
  },
  {
    slug: 'sihirli-eger',
    term: 'Sihirli Eğer',
    termEn: 'Magic If',
    group: 'oyunculuk',
    short: 'Oyuncunun "eğer ben bu durumda olsaydım ne yapardım?" sorusuyla karakterin gerçekliğine girmesini sağlayan Stanislavski tekniği.',
    body: 'Stanislavski\'nin en bilinen aracı. Oyuncudan hayali bir durumu "inanmasını" istemek yerine, "eğer" sorusuyla kendi gerçekliğine bağlamasını ister: "Eğer bu odada, bu insanla, bu bilgiyle olsaydım — ne yapardım?" Bu küçük kaydırma, yapay duygu üretimini engeller ve oyuncuyu eyleme yönlendirir.',
    related: ['stanislavski-sistemi', 'verili-durumlar'],
  },
  {
    slug: 'verili-durumlar',
    term: 'Verili Durumlar',
    termEn: 'Given Circumstances',
    group: 'oyunculuk',
    short: 'Metnin karaktere dayattığı tüm koşullar: kim, nerede, ne zaman, neden, kiminle, hangi geçmişle.',
    body: 'Bir sahnenin tüm sabit verileri. Oyuncu bunları yorumlamaz — kabul eder ve içinden çalışır. Verili durumlar iyi analiz edilmediğinde oyunculuk "genel" kalır: karakter herhangi bir yerde, herhangi biriyle konuşuyormuş gibi görünür. Sahne çalışmasının ilk adımı her zaman bu koşulların netleştirilmesidir.',
    related: ['stanislavski-sistemi', 'sihirli-eger', 'dramaturji'],
  },
  {
    slug: 'method-acting',
    term: 'Method Acting',
    termEn: 'Method Acting',
    group: 'oyunculuk',
    short: 'Lee Strasberg\'in Stanislavski\'den geliştirdiği, oyuncunun kendi duygusal geçmişini karaktere taşıdığı Amerikan oyunculuk ekolü.',
    body: 'Actors Studio\'da Lee Strasberg tarafından şekillendirildi. Stanislavski\'nin geç dönem "fiziksel eylemler" yaklaşımı yerine erken dönem "duygusal bellek" fikrini merkeze aldı. Marlon Brando, Al Pacino, Robert De Niro gibi isimlerle popüler kültüre girdi. Eleştirisi de buradan gelir: oyuncunun psikolojik güvenliğini riske atabilir ve topluluk çalışmasını zorlaştırabilir. Çağdaş eğitimde daha dengeli, eylem odaklı yaklaşımlar tercih ediliyor.',
    related: ['stanislavski-sistemi', 'duygusal-bellek', 'meisner-teknigi'],
  },
  {
    slug: 'meisner-teknigi',
    term: 'Meisner Tekniği',
    termEn: 'Meisner Technique',
    group: 'oyunculuk',
    short: 'Sanford Meisner\'ın "karşındakine gerçekten tepki ver" ilkesine dayanan, dinleme ve anlık tepki merkezli oyunculuk yöntemi.',
    body: 'Meisner\'ın tanımıyla oyunculuk: "hayali koşullar altında gerçekçi yaşamak." Yöntemin kalbi tekrar egzersizidir (repetition exercise): iki oyuncu birbirlerinde gördüklerini tekrar ederek, kafadan değil karşısındakinden beslenmeyi öğrenir. Duygusal bellek yerine partnere odaklanmayı önerir. Kamera önü oyunculuğunda özellikle etkilidir çünkü anlık ve küçük tepkileri güçlendirir.',
    related: ['method-acting', 'stanislavski-sistemi', 'dogaclama'],
    link: { label: 'Camera Praxis', href: '/atolyeler/camera-praxis' },
  },
  {
    slug: 'duygusal-bellek',
    term: 'Duygusal Bellek',
    termEn: 'Emotional Memory / Affective Memory',
    group: 'oyunculuk',
    short: 'Oyuncunun kendi geçmişindeki bir duyguyu hatırlayarak sahnede kullanması tekniği.',
    body: 'Stanislavski\'nin erken dönem çalışmalarından. Oyuncu, karakterin yaşadığına benzer bir duyguyu kendi hayatından çağırır. Güçlü ama riskli bir araç: tekrarlanabilirliği düşüktür ve oyuncuyu duygusal olarak yıpratabilir. Stanislavski kendisi de sonraki yıllarda bu tekniği geri plana atıp fiziksel eylemler yöntemine yöneldi.',
    related: ['stanislavski-sistemi', 'method-acting'],
  },
  {
    slug: 'dogaclama',
    term: 'Doğaçlama',
    termEn: 'Improvisation',
    group: 'oyunculuk',
    short: 'Önceden yazılmış metin olmadan, anlık olarak sahne, karakter ve diyalog üretme pratiği.',
    body: 'Hem bir performans formu hem bir eğitim aracı. Temel kuralı "evet, ve…" (yes, and): partnerin önerisini kabul et ve üzerine ekle. Reddetme (blocking) sahneyi öldürür. Doğaçlama oyuncunun anda kalma, dinleme ve risk alma kaslarını çalıştırır. Keith Johnstone ve Viola Spolin bu alanın iki temel ismidir.',
    related: ['meisner-teknigi', 'devising'],
  },
  {
    slug: 'sahne-korkusu',
    term: 'Sahne Korkusu',
    termEn: 'Stage Fright',
    group: 'oyunculuk',
    short: 'Seyirci önünde performans göstermeden önce ve sırasında yaşanan fizyolojik ve psikolojik gerilim.',
    body: 'Kalp atışının hızlanması, ağız kuruluğu, titreme ve zihinsel boşluk gibi belirtilerle görülür. Deneyimli oyuncularda da devam eder — fark, bu enerjiyi yönetebilmelerindedir. Nefes çalışması, sahne öncesi rutin, ve dikkati kendinden partnere/eyleme kaydırma en etkili müdahalelerdir. Tamamen yok etmek hedef değildir; sahne korkusu aynı zamanda uyanıklık ve varlık üretir.',
    related: ['nefes-destegi', 'sahne-mevcudiyeti'],
  },
  {
    slug: 'sahne-mevcudiyeti',
    term: 'Sahne Mevcudiyeti',
    termEn: 'Stage Presence',
    group: 'oyunculuk',
    short: 'Oyuncunun sahnede, hiçbir şey yapmadığı anda bile seyircinin dikkatini tutabilme niteliği.',
    body: 'Ölçülmesi zor ama varlığı hemen fark edilen bir kalite. Karizma değildir — çalışılabilir. Bileşenleri: bedensel uyanıklık, nefesin serbestliği, dikkatin dışarıda olması ve savunmasızlığa izin verme. Kendini seyretmeyi bırakan oyuncu mevcudiyet kazanır.',
    related: ['sahne-korkusu', 'fiziksel-tiyatro'],
    link: { label: 'Oyuncunun Mevcudiyeti', href: '/atolyeler/oyuncunun-mevcudiyeti' },
  },
  {
    slug: 'dorduncu-duvar',
    term: 'Dördüncü Duvar',
    termEn: 'Fourth Wall',
    group: 'sahne',
    short: 'Sahne ile seyirci arasındaki hayali sınır; oyuncunun seyircinin varlığını yok saydığı konvansiyon.',
    body: 'Natüralist tiyatroda sahne, üç duvarı olan bir odadır; dördüncü duvar seyirciye bakan taraftır ve oyuncular onu görmezden gelir. "Dördüncü duvarı yıkmak" ise oyuncunun doğrudan seyirciye seslenmesidir — Brecht bunu bilinçli bir politik araç olarak kullandı.',
    related: ['yabancilastirma-efekti', 'naturalizm'],
  },

  // ── YAZARLIK & DRAMATURJİ ──
  {
    slug: 'dramaturji',
    term: 'Dramaturji',
    termEn: 'Dramaturgy',
    group: 'yazarlık',
    short: 'Bir metnin ya da gösterinin iç yapısını, anlam katmanlarını ve sahne mantığını inceleyen çalışma alanı.',
    body: 'İki anlamda kullanılır. Birincisi: bir oyunun kendi yapısı — nasıl kurulduğu, hangi ritimle ilerlediği, hangi soruyu sorduğu. İkincisi: prodüksiyon içinde dramaturgun işi — metni araştırmak, bağlamını çıkarmak, yönetmene ve oyunculara yapısal geri bildirim vermek. Türkiye\'de az bilinen ama bir prodüksiyonun kalitesini doğrudan belirleyen bir alandır.',
    related: ['verili-durumlar', 'catisma', 'yapi'],
    link: { label: 'Auteur Lab', href: '/atolyeler/auteur-lab' },
  },
  {
    slug: 'catisma',
    term: 'Çatışma',
    termEn: 'Conflict',
    group: 'yazarlık',
    short: 'Bir karakterin istediği şey ile önündeki engel arasındaki gerilim; dramanın temel motoru.',
    body: 'Drama, "çatışma" olmadan ilerlemez. Üç temel türü vardır: karakterin başka bir karakterle, kendisiyle ya da bir sistemle/koşulla çatışması. Sahne yazımında en sık yapılan hata, karakterlerin hemfikir olduğu sahneler yazmaktır — bu sahneler bilgi taşır ama drama üretmez.',
    related: ['dramaturji', 'yapi', 'altmetin'],
  },
  {
    slug: 'altmetin',
    term: 'Altmetin',
    termEn: 'Subtext',
    group: 'yazarlık',
    short: 'Karakterin söylediği sözün altında yatan, söylenmeyen gerçek niyet ve duygu.',
    body: 'İyi diyalog, söylenenle kastedilen arasındaki boşlukta yaşar. "Kapıyı kapatır mısın?" repliği duruma göre sevgi, öfke ya da tehdit taşıyabilir. Çehov\'un tiyatrosu altmetnin ustalık örneğidir: karakterler hava durumundan konuşurken hayatlarının çöktüğünü anlatırlar. Oyuncu için altmetin bulmak, yazarsa altmetin bırakmak temel beceridir.',
    related: ['catisma', 'dramaturji'],
  },
  {
    slug: 'yapi',
    term: 'Dramatik Yapı',
    termEn: 'Dramatic Structure',
    group: 'yazarlık',
    short: 'Bir oyunun olayları hangi sırayla ve hangi ritimle sunduğunu belirleyen iskelet.',
    body: 'Klasik model Aristoteles\'ten gelir: başlangıç, gelişme, sonuç. Freytag piramidi bunu beş adıma böler. Ama çağdaş tiyatro bu doğrusallığı sıklıkla kırar — bölümsel (episodik), döngüsel, eşzamanlı ya da parçalı yapılar kullanır. Yapı seçimi teknik değil anlamsal bir karardır: nasıl anlattığın, ne anlattığını değiştirir.',
    related: ['dramaturji', 'catisma', 'episodik-yapi'],
  },
  {
    slug: 'episodik-yapi',
    term: 'Episodik Yapı',
    termEn: 'Episodic Structure',
    group: 'yazarlık',
    short: 'Oyunun kesintisiz bir akış yerine, birbirinden görece bağımsız sahnelerden kurulduğu yapı.',
    body: 'Brecht\'in tercih ettiği biçim. Her sahne kendi başına durabilir; seyirci olayın akışına kapılmak yerine sahneler arasındaki ilişkiyi düşünmeye davet edilir. Bu, duygusal özdeşleşmeyi zayıflatıp eleştirel mesafeyi güçlendirir.',
    related: ['yapi', 'yabancilastirma-efekti'],
  },
  {
    slug: 'yabancilastirma-efekti',
    term: 'Yabancılaştırma Efekti',
    termEn: 'Verfremdungseffekt / Alienation Effect',
    group: 'yazarlık',
    short: 'Brecht\'in, seyircinin olaya kapılmasını engelleyip eleştirel düşünmesini sağlamak için kullandığı teknikler bütünü.',
    body: 'Bertolt Brecht, seyircinin karakterle özdeşleşip ağlamasını değil, sahnedeki durumun neden böyle olduğunu sormasını istedi. Bunun için: oyuncular karakterden çıkıp seyirciye seslenir, sahne değişimleri açıkta yapılır, şarkılar akışı böler, pankartlar olayı önceden duyurur. Amaç yabancılaştırmak değil — tanıdık olanı yabancı göstererek görünür kılmaktır.',
    related: ['episodik-yapi', 'dorduncu-duvar', 'epik-tiyatro'],
  },
  {
    slug: 'epik-tiyatro',
    term: 'Epik Tiyatro',
    termEn: 'Epic Theatre',
    group: 'tarih',
    short: 'Brecht\'in geliştirdiği, seyirciyi duygusal özdeşleşme yerine eleştirel düşünmeye yönlendiren tiyatro anlayışı.',
    body: 'Aristotelesçi "dramatik tiyatro"nun karşısına konumlanır. Dramatik tiyatro seyirciyi olayın içine çeker; epik tiyatro dışarıda tutar. Brecht\'e göre tiyatro dünyayı yalnızca yorumlamamalı, değiştirmeye katkı sunmalıdır. Politik tiyatronun 20. yüzyıldaki en etkili çerçevesidir.',
    related: ['yabancilastirma-efekti', 'episodik-yapi'],
  },
  {
    slug: 'monolog',
    term: 'Monolog',
    termEn: 'Monologue',
    group: 'yazarlık',
    short: 'Tek bir karakterin kesintisiz konuştuğu, genellikle bir karar anını ya da iç çatışmayı taşıyan metin parçası.',
    body: 'Soliloquy\'den farkıdır: monologda karakter sahnedeki başka birine konuşur; soliloquy\'de yalnızdır ve düşüncelerini sesli aktarır. Oyunculuk seçmelerinde en çok kullanılan formattır çünkü kısa sürede karakter inşası, metin anlayışı ve sahne varlığı hakkında bilgi verir.',
    related: ['soliloquy', 'altmetin'],
    link: { label: 'Monolog Kütüphanesi', href: '/kaynaklar/monologlar' },
  },
  {
    slug: 'soliloquy',
    term: 'Soliloquy',
    termEn: 'Soliloquy',
    group: 'yazarlık',
    short: 'Karakterin sahnede yalnızken düşüncelerini sesli olarak paylaştığı konuşma.',
    body: 'Shakespeare tiyatrosunun imzası. Hamlet\'in "To be or not to be" konuşması en bilinen örnektir. İşlevi: karakterin iç dünyasını seyirciye açmak, ve karar anını dramatik hale getirmek. Modern tiyatroda daha az kullanılır ama tek kişilik oyunlarda (monodrama) yeniden merkeze döner.',
    related: ['monolog', 'dorduncu-duvar'],
  },

  // ── SAHNE & PERFORMANS ──
  {
    slug: 'devising',
    term: 'Devising',
    termEn: 'Devised Theatre',
    group: 'sahne',
    short: 'Hazır bir metinden değil, topluluğun ortak çalışmasından doğan gösteri üretme yöntemi.',
    body: 'Yazar merkezli üretimin alternatifi. Prova salonunda doğaçlama, beden çalışması, araştırma ve tartışmayla malzeme üretilir; metin varsa süreç içinde oluşur. Yetkiyi dağıtır: her performansçı aynı zamanda yaratıcıdır. Bağımsız tiyatroda yaygın, çünkü hem ekonomik hem de kolektif üretime uygun.',
    related: ['dogaclama', 'fiziksel-tiyatro'],
  },
  {
    slug: 'fiziksel-tiyatro',
    term: 'Fiziksel Tiyatro',
    termEn: 'Physical Theatre',
    group: 'sahne',
    short: 'Anlamı öncelikle bedenin hareketiyle üreten, metni ikincil konumda tutan tiyatro biçimi.',
    body: 'Jacques Lecoq, Jerzy Grotowski ve Étienne Decroux bu alanın kurucu isimleridir. Beden metnin taşıyıcısı değil, kendisi anlatıdır. Mim, akrobasi, maske ve dans teknikleri kullanılır. Dil bariyerini aştığı için uluslararası dolaşımda güçlüdür.',
    related: ['devising', 'sahne-mevcudiyeti'],
  },
  {
    slug: 'naturalizm',
    term: 'Natüralizm',
    termEn: 'Naturalism',
    group: 'tarih',
    short: 'Sahnede gündelik hayatı olabildiğince gerçeğe yakın temsil etmeyi amaçlayan 19. yüzyıl akımı.',
    body: 'Émile Zola\'nın edebiyat kuramından tiyatroya taşındı. Karakterler kalıtım ve çevre koşullarının ürünüdür; sahne tasarımı gerçek bir odayı taklit eder; oyunculuk abartıdan arınır. Stanislavski\'nin sistemi büyük ölçüde bu akımın oyunculuk ihtiyacına verilmiş bir yanıttır.',
    related: ['dorduncu-duvar', 'stanislavski-sistemi'],
  },
  {
    slug: 'blocking',
    term: 'Blocking',
    termEn: 'Blocking',
    group: 'sahne',
    short: 'Oyuncuların sahne üzerindeki hareket ve konumlanmalarının yönetmen tarafından belirlenmesi.',
    body: 'Kim nerede durur, ne zaman hareket eder, kime doğru döner — bunlar rastgele değildir. İyi blocking görsel olarak anlam üretir: güç ilişkileri, mesafe, yalnızlık hep konumlanmayla anlatılır. Not: doğaçlama terminolojisinde "blocking" tamamen farklı bir anlam taşır (partnerin önerisini reddetme).',
    related: ['dogaclama', 'mizansen'],
  },
  {
    slug: 'mizansen',
    term: 'Mizansen',
    termEn: 'Mise-en-scène',
    group: 'sahne',
    short: 'Sahnedeki her görsel unsurun — dekor, ışık, kostüm, hareket — bütünsel düzenlenişi.',
    body: 'Fransızcadan gelir: "sahneye koymak". Yönetmenin imzası burada görülür. Aynı metin iki farklı mizansenle bambaşka anlamlar üretebilir. Sinemada da kullanılan bir terimdir ve orada kadraj içindeki her şeyi kapsar.',
    related: ['blocking', 'dramaturji'],
  },
  {
    slug: 'prova',
    term: 'Prova',
    termEn: 'Rehearsal',
    group: 'sahne',
    short: 'Gösteri öncesi, metnin sahneye taşındığı ve tekrarlanarak inşa edildiği çalışma süreci.',
    body: 'Aşamaları genellikle şöyledir: masa başı okuma (table read), sahne çalışması, blocking, teknik prova (dekor/ışık/ses ile), kostümlü prova (dress rehearsal), genel prova. Bağımsız tiyatroda prova süresi ekonomik kısıtlarla belirlenir ve çoğu zaman ideal olanın altındadır.',
    related: ['blocking', 'mizansen'],
  },

  // ── MÜZİKAL & DANS ──
  {
    slug: 'muzikal-tiyatro',
    term: 'Müzikal Tiyatro',
    termEn: 'Musical Theatre',
    group: 'müzikal',
    short: 'Oyunculuk, şarkı ve dansın tek bir anlatı içinde birleştiği sahne formu.',
    body: 'Üç disiplinin dengede olması gerekir — hiçbiri diğerini bastırmaz. Şarkı, dramatik ihtiyacın devamıdır: karakter konuşarak anlatamadığı noktada şarkı söyler, şarkıyla da yetmediğinde dans eder. Bu ilke müzikal yazımının ve oyunculuğunun temelidir.',
    related: ['book-musical', 'belting', 'theatre-dance'],
    link: { label: 'Techne Musical Lab', href: '/atolyeler/techne-musical-lab' },
  },
  {
    slug: 'book-musical',
    term: 'Book Musical',
    termEn: 'Book Musical',
    group: 'müzikal',
    short: 'Şarkıların bağımsız numaralar değil, sürekli bir hikâyenin parçası olduğu müzikal formu.',
    body: '1943\'te Oklahoma! ile yerleşen model. Öncesinde müzikaller büyük ölçüde birbirinden kopuk şarkı ve skeçlerden oluşuyordu. Book musical\'da her şarkı olayı ilerletir ya da karakteri değiştirir — "kaldırıldığında hikâye eksilir" testi geçerlidir.',
    related: ['muzikal-tiyatro', 'i-want-song'],
  },
  {
    slug: 'i-want-song',
    term: '"I Want" Şarkısı',
    termEn: 'I Want Song',
    group: 'müzikal',
    short: 'Müzikalin başlarında yer alan, ana karakterin ne istediğini seyirciye açan şarkı.',
    body: 'Neredeyse her klasik müzikalde vardır ve dramaturjik olarak zorunludur: seyirci karakterin arzusunu bilmeden yolculuğu takip edemez. Karakterin bu şarkıda söylediği arzu, finalde ya gerçekleşir ya da anlamı değişir.',
    related: ['book-musical', 'muzikal-tiyatro'],
  },
  {
    slug: 'belting',
    term: 'Belting',
    termEn: 'Belting',
    group: 'müzikal',
    short: 'Göğüs rezonansını yüksek perdelere taşıyan, güçlü ve parlak müzikal şarkı tekniği.',
    body: 'Broadway sesinin karakteristik rengi. Doğru yapıldığında güçlü ve taşıyıcıdır; yanlış yapıldığında ses tellerini zorlar ve kalıcı hasara yol açabilir. Destek (nefes), larinks pozisyonu ve rezonans ayarı doğru kurulmadan çalışılmamalıdır. Mix voice ile birlikte öğretilir.',
    related: ['mix-voice', 'nefes-destegi', 'muzikal-tiyatro'],
  },
  {
    slug: 'mix-voice',
    term: 'Mix Voice',
    termEn: 'Mixed Voice',
    group: 'müzikal',
    short: 'Göğüs ve kafa rezonansının dengelenmesiyle elde edilen, geniş aralıkta rahat kullanılabilen ses.',
    body: 'Müzikal repertuvarının çoğu bu bölgede yazılır. Ses kırılmadan (break/passaggio) geçiş yapabilmeyi sağlar. Belting\'in güvenli temeli mix voice\'tır — önce karışım kurulur, sonra parlaklık eklenir.',
    related: ['belting', 'nefes-destegi'],
  },
  {
    slug: 'nefes-destegi',
    term: 'Nefes Desteği',
    termEn: 'Breath Support',
    group: 'müzikal',
    short: 'Diyafram ve karın kaslarıyla hava akışının kontrollü biçimde yönetilmesi; hem şarkının hem sahne konuşmasının temeli.',
    body: 'Sesin gücü boğazdan değil, nefesin yönetiminden gelir. Destek doğru kurulduğunda boğaz serbest kalır, ses yorulmaz ve duygusal iniş çıkışlar teknik olarak taşınabilir. Oyunculuk için de aynı ölçüde önemlidir: nefesi tutulan oyuncu duygusunu da tutar.',
    related: ['belting', 'mix-voice', 'sahne-korkusu'],
    link: { label: 'Ses & Nefes Egzersizleri', href: '/kaynaklar/ses-nefes' },
  },
  {
    slug: 'theatre-dance',
    term: 'Theatre Dance',
    termEn: 'Theatre Dance',
    group: 'müzikal',
    short: 'Teknik gösteriden çok karakter ve anlatı taşımayı amaçlayan, müzikal sahnesine özgü dans dili.',
    body: 'Balede hedef form ve teknik mükemmelliktir; theatre dance\'te hedef anlatıdır. Dansçı bir karakteri, bir ilişkiyi ya da bir duygusal dönüşümü hareketle taşır. Jazz temeli üzerine kurulur; Fosse, Robbins ve Bennett bu dilin belirleyici koreograflarıdır.',
    related: ['jazz-dans', 'muzikal-tiyatro'],
    link: { label: 'Broadway Musical Dance', href: '/atolyeler/broadway-musical-dance' },
  },
  {
    slug: 'jazz-dans',
    term: 'Jazz Dans',
    termEn: 'Jazz Dance',
    group: 'müzikal',
    short: 'Afro-Amerikan dans geleneğinden doğan, izolasyon, senkop ve keskin aksanlarla tanımlanan dans türü.',
    body: 'Broadway dansının teknik temeli. Karakteristikleri: beden bölgelerinin bağımsız hareketi (izolasyon), ritmin beklenmedik yerlerinde vurgu (senkop) ve yüksek enerji. Bale terminolojisini kullanır ama estetiği tamamen farklıdır.',
    related: ['theatre-dance', 'muzikal-tiyatro'],
  },
]

export const TERM_GROUPS = [
  { key: 'oyunculuk', label: 'Oyunculuk', desc: 'Sahne pratiği, yöntemler, teknikler' },
  { key: 'yazarlık',  label: 'Yazarlık & Dramaturji', desc: 'Metin, yapı, anlam' },
  { key: 'sahne',     label: 'Sahne & Prodüksiyon', desc: 'Prova salonundan sahneye' },
  { key: 'müzikal',   label: 'Müzikal & Dans', desc: 'Şan, hareket, Broadway dili' },
  { key: 'tarih',     label: 'Akımlar & Tarih', desc: 'Tiyatroyu şekillendiren düşünceler' },
] as const

// ── MONOLOG KÜTÜPHANESİ ──────────────────────────────────────────
export type Monologue = {
  slug: string
  play: string
  playEn?: string
  author: string
  year: string
  character: string
  gender: 'kadın' | 'erkek' | 'nötr'
  age: string
  lang: 'tr' | 'en'
  length: 'kısa' | 'orta' | 'uzun'   // <1dk / 1-2dk / 2dk+
  tone: string
  context: string      // sahnenin bağlamı
  note: string         // oyuncuya çalışma notu
  publicDomain: boolean
}

export const MONOLOGUES: Monologue[] = [
  {
    slug: 'hamlet-to-be-or-not-to-be',
    play: 'Hamlet',
    author: 'William Shakespeare',
    year: '1601',
    character: 'Hamlet',
    gender: 'nötr',
    age: '20–35',
    lang: 'en',
    length: 'orta',
    tone: 'Felsefi, içe dönük, kararsızlık',
    context: 'Hamlet yalnızdır. Babasının intikamını almakla yaşamaya devam etmek arasında sıkışmıştır. Bu konuşma bir karar anı değil — kararsızlığın kendisinin sahnelenmesidir.',
    note: 'En çok çalışılan ve en çok yanlış çalışılan metin. Tuzağı: "ünlü konuşma" olarak seslendirmek. Çözümü: kime konuştuğunu netleştir. Kendine mi, seyirciye mi, Tanrı\'ya mı? Seçim, tüm ritmi değiştirir. Anlamı ezberleme — soruyu gerçekten sor.',
    publicDomain: true,
  },
  {
    slug: 'macbeth-tomorrow',
    play: 'Macbeth',
    author: 'William Shakespeare',
    year: '1606',
    character: 'Macbeth',
    gender: 'nötr',
    age: '30–55',
    lang: 'en',
    length: 'kısa',
    tone: 'Boşluk, tükenmişlik, nihilizm',
    context: 'Lady Macbeth\'in ölüm haberini almıştır. Tepkisi ağıt değil — anlamın tamamen çöküşüdür.',
    note: 'Kısa ama en zor metinlerden. Tuzağı: dramatik yoğunluk üretmeye çalışmak. Bu konuşmanın gücü boşluğunda. Duygu değil, duygunun bittiği yer oynanır. Seçmelerde çok kısa olduğu için tercih edilir — ama iyi taşıyabilmek deneyim ister.',
    publicDomain: true,
  },
  {
    slug: 'lady-macbeth-unsex-me',
    play: 'Macbeth',
    author: 'William Shakespeare',
    year: '1606',
    character: 'Lady Macbeth',
    gender: 'kadın',
    age: '25–45',
    lang: 'en',
    length: 'orta',
    tone: 'Yakarış, kararlılık, dönüşüm talebi',
    context: 'Kocasının kral olacağını öğrenmiştir ve onun bunu yapacak kadar acımasız olmadığını bilir. Kendisini dönüştürmesi için karanlık güçlere seslenir.',
    note: 'Bir "kötü kadın" klişesi olarak oynanırsa ölür. Bu bir yakarıştır — yani karakterin kendisinde olmayan bir şeyi istemesidir. Zayıflığı bul, güç oradan gelsin. Kadın oyuncular için seçmelerde en güçlü Shakespeare seçeneklerinden.',
    publicDomain: true,
  },
  {
    slug: 'nora-doll-house',
    play: 'Bir Bebek Evi',
    playEn: "A Doll's House",
    author: 'Henrik Ibsen',
    year: '1879',
    character: 'Nora',
    gender: 'kadın',
    age: '25–40',
    lang: 'en',
    length: 'uzun',
    tone: 'Uyanış, netlik, ayrılık',
    context: 'Final sahnesi. Nora, kocasına sekiz yıllık evliliğinde hiç konuşmadıklarını söyler ve gitmeye karar verir.',
    note: 'Öfke sahnesi değil. Nora bağırmaz — ilk defa net konuşur. Sakinlik en güçlü seçimdir. Tiyatro tarihinin en önemli çıkış anlarından biri; kapının kapanma sesi modern dramanın başlangıcı sayılır.',
    publicDomain: true,
  },
  {
    slug: 'sonya-uncle-vanya',
    play: 'Vanya Dayı',
    playEn: 'Uncle Vanya',
    author: 'Anton Çehov',
    year: '1897',
    character: 'Sonya',
    gender: 'kadın',
    age: '18–30',
    lang: 'en',
    length: 'orta',
    tone: 'Teselli, dayanma, kırılgan umut',
    context: 'Oyunun son konuşması. Herkes gitmiştir, hiçbir şey değişmemiştir. Sonya, Vanya\'ya "yaşamaya devam edeceğiz" der.',
    note: 'Çehov\'un en zor tonlarından: umut mu, teslimiyet mi? İkisi de. Duygusallaştırma. Sonya kendini de ikna etmeye çalışıyor — bu çift katman oynanmalı. Ağlamak kolay çözüm, ağlamamak doğru olan.',
    publicDomain: true,
  },
  {
    slug: 'treplev-seagull',
    play: 'Martı',
    playEn: 'The Seagull',
    author: 'Anton Çehov',
    year: '1896',
    character: 'Treplev',
    gender: 'erkek',
    age: '20–30',
    lang: 'en',
    length: 'orta',
    tone: 'Öfke, sanatsal isyan, kırgınlık',
    context: 'Genç yazar Treplev, annesinin temsil ettiği eski tiyatroya ve kendi başarısızlığına isyan eder.',
    note: 'Genç oyuncular için ideal — çünkü karakterin yaşı ve arayışı örtüşür. Tuzağı: sadece öfke oynamak. Altında derin bir onaylanma ihtiyacı var. Anneye duyulan sevgi de sahnede olmalı.',
    publicDomain: true,
  },
  {
    slug: 'medea-revenge',
    play: 'Medea',
    author: 'Euripides',
    year: 'MÖ 431',
    character: 'Medea',
    gender: 'kadın',
    age: '30–50',
    lang: 'en',
    length: 'uzun',
    tone: 'İhanet, hesaplaşma, kararlılık',
    context: 'Kocası Jason onu terk etmiştir. Medea, kadınların toplumdaki konumunu anlatır ve intikamını planlar.',
    note: 'Antik metinler retorik olarak yazılır — argüman taşır. Modern psikolojik oyunculukla değil, düşüncenin gücüyle taşınmalı. Her cümle bir sonrakini doğurur. Nefes ve ritim kritik.',
    publicDomain: true,
  },
  {
    slug: 'shylock-hath-not-a-jew',
    play: 'Venedik Taciri',
    playEn: 'The Merchant of Venice',
    author: 'William Shakespeare',
    year: '1596',
    character: 'Shylock',
    gender: 'nötr',
    age: '35–65',
    lang: 'en',
    length: 'orta',
    tone: 'Savunma, öfke, insanlık talebi',
    context: 'Shylock, kendisini aşağılayanlara bir Yahudi\'nin de insan olduğunu hatırlatır.',
    note: 'Metnin gücü mantık kurgusunda: soru-soru-soru, sonra sonuç. Duyguyu yapıya bindir. Retorik bir tırmanış — başlangıçtaki ton ile sondaki aynı olmamalı.',
    publicDomain: true,
  },
  {
    slug: 'jaques-seven-ages',
    play: 'Nasıl Hoşunuza Giderse',
    playEn: 'As You Like It',
    author: 'William Shakespeare',
    year: '1599',
    character: 'Jaques',
    gender: 'nötr',
    age: '30–60',
    lang: 'en',
    length: 'orta',
    tone: 'Alaycı, gözlemci, melankolik',
    context: '"Bütün dünya bir sahne" — Jaques, insan ömrünü yedi role böler.',
    note: 'Karakter değil, gözlem konuşuyor gibi görünür — ama bu bir tuzak. Jaques\'in kendi melankolisi metnin altında akar. Yedi çağı yedi farklı renkle çalış, tek tonda oynama.',
    publicDomain: true,
  },
  {
    slug: 'antigone-defiance',
    play: 'Antigone',
    author: 'Sophokles',
    year: 'MÖ 441',
    character: 'Antigone',
    gender: 'kadın',
    age: '17–30',
    lang: 'en',
    length: 'orta',
    tone: 'Direniş, ilke, kabullenme',
    context: 'Kralın yasasına karşı gelip kardeşini gömmüştür. Yakalandığında pişmanlık göstermez.',
    note: 'Genç kadın oyuncular için en güçlü klasik seçeneklerden. Antigone haklı olduğunu bilir — bu bir tartışma değil, bir beyandır. Savunmaya geçme, açıkla.',
    publicDomain: true,
  },
  {
    slug: 'algernon-importance',
    play: 'Ciddi Olmanın Önemi',
    playEn: 'The Importance of Being Earnest',
    author: 'Oscar Wilde',
    year: '1895',
    character: 'Algernon',
    gender: 'erkek',
    age: '22–35',
    lang: 'en',
    length: 'kısa',
    tone: 'Komik, hafif, zeki',
    context: 'Algernon, evlilik ve toplum kuralları üzerine tersine çevrilmiş bir mantık kurar.',
    note: 'Komedi monologu bulmak zordur — bu yüzden değerli. Wilde\'ın mizahı ritimde: cümle uzun kurulur, son kelimede devrilir. Zamanlama her şey. Komik olmaya çalışma, ciddi oyna — komik olan durum.',
    publicDomain: true,
  },
  {
    slug: 'gwendolen-importance',
    play: 'Ciddi Olmanın Önemi',
    playEn: 'The Importance of Being Earnest',
    author: 'Oscar Wilde',
    year: '1895',
    character: 'Gwendolen',
    gender: 'kadın',
    age: '20–35',
    lang: 'en',
    length: 'kısa',
    tone: 'Komik, kararlı, absürt ciddiyet',
    context: 'Gwendolen, bir erkeği yalnızca "Ernest" adını taşıdığı için sevebileceğini açıklar.',
    note: 'Absürt bir önermeyi mutlak bir ciddiyetle savunmak — İngiliz komedisinin kalbi. Karakterin kendi mantığına tam inanması gerekir. Göz kırpma yok.',
    publicDomain: true,
  },
  {
    slug: 'hedda-gabler-boredom',
    play: 'Hedda Gabler',
    author: 'Henrik Ibsen',
    year: '1891',
    character: 'Hedda',
    gender: 'kadın',
    age: '25–40',
    lang: 'en',
    length: 'orta',
    tone: 'Sıkışmışlık, soğuk öfke, tehlike',
    context: 'Hedda, hayatının ne kadar dar ve anlamsız olduğunu anlatır — ve bundan kaçmak için başkalarının hayatıyla oynamaya başlar.',
    note: 'Sempatik olmaya çalışma. Hedda\'nın gücü tam da rahatsız edici olmasında. Soğukluğun altındaki panik oynanırsa karakter üç boyut kazanır.',
    publicDomain: true,
  },
  {
    slug: 'puck-epilogue',
    play: 'Bir Yaz Gecesi Rüyası',
    playEn: "A Midsummer Night's Dream",
    author: 'William Shakespeare',
    year: '1596',
    character: 'Puck',
    gender: 'nötr',
    age: '18–40',
    lang: 'en',
    length: 'kısa',
    tone: 'Oyunbaz, doğrudan, büyülü',
    context: 'Oyunun sonu. Puck doğrudan seyirciye seslenir ve tüm olanların bir rüya olabileceğini söyler.',
    note: 'Doğrudan seyirciye konuşma pratiği için mükemmel. Dördüncü duvar yok — göz teması gerçek olmalı. Kısa, ritmik, hafif. Seçmelerde enerji göstermek için ideal.',
    publicDomain: true,
  },
  {
    slug: 'konstantin-nina-seagull',
    play: 'Martı',
    playEn: 'The Seagull',
    author: 'Anton Çehov',
    year: '1896',
    character: 'Nina',
    gender: 'kadın',
    age: '18–30',
    lang: 'en',
    length: 'uzun',
    tone: 'Yıkım, direnç, olgunlaşma',
    context: 'Son perde. Nina yıllar sonra döner; hayalleri kırılmış ama oyunculuktan vazgeçmemiştir.',
    note: 'Çehov\'un en talepkâr kadın monologlarından. İki zaman katmanı var: geçmişteki genç kız ve şimdiki yorgun kadın. İkisi arasında gidip gelir. Acıma değil, dayanıklılık oyna.',
    publicDomain: true,
  },
]

// ── SES & NEFES EGZERSİZLERİ ─────────────────────────────────────
export type Exercise = {
  slug: string
  title: string
  goal: string
  duration: string
  level: 'başlangıç' | 'orta' | 'ileri'
  steps: string[]
  warning?: string
  group: 'nefes' | 'ses' | 'artikülasyon' | 'beden'
}

export const EXERCISES: Exercise[] = [
  {
    slug: 'diyafram-farkindaligi',
    title: 'Diyafram Farkındalığı',
    goal: 'Nefesin göğüsten değil karından geldiğini bedene öğretmek',
    duration: '5 dakika',
    level: 'başlangıç',
    group: 'nefes',
    steps: [
      'Sırtüstü yere uzan. Dizler bükülü, ayak tabanları yerde.',
      'Bir elini göğsüne, diğerini göbeğinin üstüne koy.',
      'Burnundan yavaşça nefes al. Göğsündeki el hareketsiz kalmalı, göbeğindeki el yükselmeli.',
      'Ağzından "sss" sesiyle yavaşça ver. Göbek içeri doğru çekilsin.',
      '10 tekrar. Sonra ayağa kalk ve aynı hissi ayakta bul.',
    ],
    warning: 'Baş dönmesi hissedersen dur ve normal nefese dön. Aşırı derin nefes hiperventilasyona yol açabilir.',
  },
  {
    slug: 'sss-sayimi',
    title: 'Nefes Uzatma — "Sss" Sayımı',
    goal: 'Nefes kapasitesini ve hava akışı kontrolünü ölçmek ve geliştirmek',
    duration: '3 dakika',
    level: 'başlangıç',
    group: 'nefes',
    steps: [
      'Ayakta dur, omuzlar gevşek.',
      'Karından derin nefes al (4 sayıda).',
      '"Sss" sesiyle mümkün olduğunca yavaş ve düzenli ver. Saymaya devam et.',
      'Kaça kadar gittiğini not al. Bu senin başlangıç ölçümün.',
      '3 tekrar yap, aralarda normal nefes al. Haftalar içinde sayının arttığını göreceksin.',
    ],
    warning: 'Ses düzensizleşiyorsa hava kontrolsüz kaçıyor demektir — hızı azalt, süreyi zorlamayı bırak.',
  },
  {
    slug: 'destekli-ah',
    title: 'Destekli "Ah" — Sesi Nefese Bağlama',
    goal: 'Boğazı serbest tutarak sesi nefes desteğiyle üretmek',
    duration: '5 dakika',
    level: 'başlangıç',
    group: 'ses',
    steps: [
      'Karından nefes al.',
      'Çeneni gevşet, ağzını rahatça aç.',
      'Rahat bir orta perdede "ahhh" sesi çıkar. Bağırma — akıt.',
      'Elini karnına koy: ses çıkarken karın kasların hafifçe devrede olmalı, boğazın gergin olmamalı.',
      'Aynı sesi giderek yükselen perdelerde tekrarla. Boğaz gerilirse geri in.',
    ],
    warning: 'Boğazda kaşıntı, yanma ya da kısılma hissi varsa hemen dur. Ses teknik çalışması ağrılı olmamalıdır.',
  },
  {
    slug: 'dudak-titremesi',
    title: 'Dudak Titremesi (Lip Trill)',
    goal: 'Ses tellerini ısıtmak, boğazı gevşetmek, aralığı güvenle taramak',
    duration: '3 dakika',
    level: 'başlangıç',
    group: 'ses',
    steps: [
      'Dudaklarını gevşet, hafifçe kapat.',
      'Nefesi dışarı vererek dudakların titremesini sağla ("brrrr").',
      'Titreme sürerken bir ses ekle — düşük bir perdeden başla.',
      'Sesi yavaşça yukarı ve aşağı kaydır, tüm aralığı tara.',
      '5 tur. Ses kırılırsa devam et — bu egzersizin amacı zaten geçiş bölgelerini yumuşatmak.',
    ],
  },
  {
    slug: 'rezonans-mmm',
    title: 'Rezonans Bulma — Hümming',
    goal: 'Sesin kafa ve maske rezonansını hissetmek, projeksiyonu artırmak',
    duration: '4 dakika',
    level: 'orta',
    group: 'ses',
    steps: [
      'Dudaklar kapalı, dişler ayrı, çene gevşek.',
      'Rahat bir perdede "mmm" sesi çıkar.',
      'Parmaklarını burun kemiğine ve yanaklarına koy — titreşimi hissetmelisin.',
      'Titreşim yoksa perdeni değiştir, hissedene kadar ara.',
      'Titreşimi bulduğunda "mmm-aaa" diye aç. Rezonansı açık sese taşımaya çalış.',
    ],
  },
  {
    slug: 'tekerleme-serisi',
    title: 'Artikülasyon — Tekerleme Serisi',
    goal: 'Dil, dudak ve çene kaslarını hızlandırmak; sahne netliği kazanmak',
    duration: '5 dakika',
    level: 'başlangıç',
    group: 'artikülasyon',
    steps: [
      'Önce çok yavaş ve abartılı biçimde söyle — her hece net olsun.',
      '"Bir berber bir berbere bre berber gel beraber bir berber dükkânı açalım demiş."',
      '"Şu köşe yaz köşesi, şu köşe kış köşesi, ortada su şişesi."',
      '"Kartal kalkar dal sarkar, dal sarkar kartal kalkar."',
      'Her birini üç hızda tekrarla: çok yavaş → normal → hızlı. Hızda netlik kaybolursa yavaşa dön.',
    ],
  },
  {
    slug: 'kalem-tekniği',
    title: 'Kalem Tekniği',
    goal: 'Artikülasyon kaslarını zorlayarak netliği artırmak',
    duration: '3 dakika',
    level: 'orta',
    group: 'artikülasyon',
    steps: [
      'Temiz bir kalemi dişlerinin arasına yatay koy.',
      'Bir metin parçasını (monolog ya da tekerleme) kalemi tutarak oku. Anlaşılır olmaya çalış.',
      '1 dakika devam et.',
      'Kalemi çıkar ve aynı metni tekrar oku. Netliğin belirgin şekilde arttığını duyacaksın.',
    ],
    warning: 'Kalem temiz olmalı. Çene ağrısı hissedersen süreyi kısalt.',
  },
  {
    slug: 'omurga-serbestlesme',
    title: 'Omurga Serbestleşmesi',
    goal: 'Nefesin önündeki bedensel engelleri kaldırmak',
    duration: '5 dakika',
    level: 'başlangıç',
    group: 'beden',
    steps: [
      'Ayakta dur, ayaklar kalça genişliğinde.',
      'Başından başlayarak omur omur aşağı sarkmaya başla. Kollar serbest bıraksın.',
      'Tamamen sarktığında 3 nefes al. Sırtın nefesle genişlediğini hisset.',
      'Aynı yavaşlıkta, omur omur yukarı dizil. Baş en son gelsin.',
      '3 tekrar.',
    ],
    warning: 'Bel ya da boyun rahatsızlığın varsa bu egzersizi bir uzmana danışmadan yapma.',
  },
  {
    slug: 'sahne-oncesi-rutin',
    title: 'Sahne Öncesi 4 Dakikalık Rutin',
    goal: 'Sahne korkusunu yönetmek, bedeni ve sesi hazır hale getirmek',
    duration: '4 dakika',
    level: 'orta',
    group: 'beden',
    steps: [
      '1 dk — Omurga serbestleşmesi: iki tekrar, yavaş.',
      '1 dk — Nefes: 4 sayıda al, 6 sayıda ver. Verişi uzatmak sinir sistemini yatıştırır.',
      '1 dk — Dudak titremesi ile ses ısıtma.',
      '1 dk — Dikkati dışarı ver: odada beş nesne say, üç ses duy. Bu, kendini seyretmeyi keser.',
      'Sahneye çık.',
    ],
    warning: 'Bu rutin performans kaygısını yönetmeye yardımcı olur; klinik düzeyde anksiyete yaşıyorsan bir uzmandan destek almak gerekir.',
  },
  {
    slug: 'ingilizce-rezonans',
    title: 'İngilizce Konuşurken Rezonans',
    goal: 'İngilizce sahne konuşmasında ses taşıyıcılığını artırmak',
    duration: '5 dakika',
    level: 'orta',
    group: 'artikülasyon',
    steps: [
      'Türkçe konuşurken ses genelde daha önde ve düz üretilir; İngilizce daha geniş bir rezonans alanı ister.',
      '"Mmm" ile rezonansı bul (bkz. hümming egzersizi).',
      'Rezonansı koruyarak şu sesleri uzat: "maa — mee — moo — may — my".',
      'Sonra kısa bir İngilizce cümle söyle: "The rain in Spain stays mainly in the plain."',
      'Rezonansı kaybettiğin anı fark et ve oradan tekrarla.',
    ],
  },
]

export const EXERCISE_GROUPS = [
  { key: 'nefes', label: 'Nefes', desc: 'Her şeyin temeli' },
  { key: 'ses', label: 'Ses', desc: 'Isınma ve rezonans' },
  { key: 'artikülasyon', label: 'Artikülasyon', desc: 'Netlik ve taşıyıcılık' },
  { key: 'beden', label: 'Beden', desc: 'Serbestlik ve hazırlık' },
] as const
